version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.static
    ports:
     - "8080:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
     - "5000:5000"