# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=5, max_digits=20)),
                ('statement', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='statemententry',
            name='company',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='analyticentry',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='analyticentry',
            name='type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='StatementEntry',
        ),
        migrations.AddField(
            model_name='reportedentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
