version: '3'
services:
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.static
#    ports:
#     - "8080:80"
  api:
    build: .
    env_file:
      - env_file
    ports:
     - "5000:5000"
    volumes:
      - .:/code
  db:
    image: postgres
    env_file:
      - env_file
    ports:
    - "5432:5432"
